version: '3'

services:
  app:
    image: quay.io/keycloak/keycloak:18.0
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
    ports:
      - 8081:8080 # maquina:docker
    command:
      - start-dev
